# Generated by Django 5.2 on 2025-05-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_countryinfo_cca2'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='countryinfo',
            index=models.Index(fields=['name'], name='api_country_name_5e2656_idx'),
        ),
    ]
